kind: Pod
apiVersion: v1
metadata:
  labels:
    app: node-density-{{.Iteration}}
  name: {{.JobName}}-{{.Iteration}}
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/worker
            operator: Exists
          - key: node-role.kubernetes.io/infra
            operator: DoesNotExist
          - key: node-role.kubernetes.io/workload
            operator: DoesNotExist
  tolerations:
  - key: os
    value: Windows
    effect: NoSchedule
  containers:
  - image: {{.containerImage}}
    name: node-density
    resources:
      limits:
        memory: "1Gi"
      requests:
        memory: "10Mi"
        cpu: "10m"
    imagePullPolicy: IfNotPresent
    command:
      - /bin/python3
      -  -c
      - |
        import os
        import time
        x = 0
        while(x<12):
          time.sleep(1)
          print("here", os.getpid(), x)
          os.fork();
          x+=1
        print("done", os.getpid(), x)
